name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Clonage du dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Installation des dépendances Angular
      - name: Install Angular dependencies
        run: npm install --legacy-peer-deps
        working-directory: angular-app

      # Étape 3 : Fixer les permissions pour Angular CLI
      - name: Fix permissions for Angular CLI
        run: chmod +x node_modules/.bin/ng
        working-directory: angular-app


      # Étape 4 : Build Angular en utilisant le binaire local
      - name: Build Angular
        run: ./node_modules/.bin/ng build --configuration production
        working-directory: angular-app


      # Étape 5 : Setup .NET et build/publish
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Build .NET solution
        run: dotnet build ./dotnet-api/dotnet-api.csproj --configuration Release

      - name: Publish .NET
        run: dotnet publish ./dotnet-api/dotnet-api.csproj -c Release -o publish

      # Étape 6 : Déploiement sur EC2
      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > id_rsa
          chmod 600 id_rsa

          if [[ "${{ github.ref_name }}" == "dev" ]]; then
            IP=${{ secrets.IP_EC2_TEST }}
          elif [[ "${{ github.ref_name }}" == "prod" ]]; then
            IP=${{ secrets.IP_EC2_PROD }}
          fi

          scp -i id_rsa -r ./angular-app/dist/* ec2-user@$IP:/tmp/angular
          scp -i id_rsa -r ./publish/* ec2-user@$IP:/tmp/dotnet

          ssh -i id_rsa ec2-user@$IP << 'EOT'
            sudo rm -rf /var/www/angular-app
            sudo mv /tmp/angular /var/www/angular-app
            sudo rm -rf ~/dotnet
            sudo mv /tmp/dotnet ~/dotnet
            sudo systemctl restart nginx
            sudo systemctl restart dotnet-api
          EOT
        working-directory: .
